### ISSUE TITLE
Cluster recovery, ERROR: extension "timescaledb" must be preloaded

### ISSUE THREAD

**Issue by alessandroros** [imusmanmalik/cloudnative-pg-timescaledb-postgis-containers#49]
Hi,
thanks a lot for this great Docker image — I'm using it successfully in production. 🙏

I have a question regarding a cluster restore scenario. When I recover a CNPG cluster from an S3 backup using this image and then promote it to be a writable "primary" (i.e., no longer in recovery mode), TimescaleDB is not loaded.

When I try to use Timescale functionality, I get this error:

`ERROR: extension "timescaledb" must be preloaded.
`
Here’s my recovery cluster manifest:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-prod-restored
  namespace: pg-restore
spec:
  instances: 2
  imageName: pg-timescaledb-preloaded:15.3.4-patched
  superuserSecret:
    name: pg-superuser
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - timescaledb
  storage:
    size: 680Gi
    storageClass: ibmc-vpc-block-retain-10iops-tier
  bootstrap:
    recovery:
      source: clusterBackup
      recoveryTarget:
        targetTime: "2025-03-18 21:45:01.00000+00"
  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://postgres-timescale-sdf-mystuff-db-prod/
        serverName: sdf-mystuff-db-prod
        endpointURL: https://minio-api.mystuff.com
        s3Credentials:
          accessKeyId:
            name: minio-restore-secret
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: minio-restore-secret
            key: SECRET_ACCESS_KEY
``` 
I tried several confs, as you see here I'm setting
```yaml
postgresql:
    shared_preload_libraries:
      - timescaledb
```
but it doesn't change, since I think recovery do not "allow" shared_preload_libraries to be set.  I also tried to baked in the shared_preload_libraries in the Dockerfile (pg-timescaledb-preloaded:15.3.4-patched)
```Dockerfile 
FROM ghcr.io/imusmanmalik/timescaledb-postgis:15-3.4-42
RUN echo "shared_preload_libraries = 'timescaledb'" >> /usr/share/postgresql/postgresql.conf.sample
```

I did it because I thought that probably inserting it automatically would have solved the problem, but it didn't help.

After investigating, I suspect the recovery bootstrap mode is not honoring the shared_preload_libraries field, and CNPG may be defaulting it to an empty string (""), which overrides the value baked into the image.

Interestingly, in the original running production cluster (also using TimescaleDB), I see that shared_preload_libraries is also showing as empty string "", but there the extension is working properly.

Anyone knowing something about it? Any help, tips, would be really appriciated.

Alessandro

**Comment by imusmanmalik** [comment]
Hi @alessandroros,

You’re raising a very valid and important question, and I think you’re spot-on in diagnosing what’s going on. This is a common stumbling block when working with CloudNativePG’s recovery mechanism together with extensions like TimescaleDB, which require shared_preload_libraries to be set before startup.

Let me break down what’s actually happening.

By default, both PostgreSQL and CloudNativePG initialize shared_preload_libraries as empty, which is expected. This is documented in CNPG’s official docs here:

> The shared_preload_libraries option is empty by default. Although you can override its content, it’s recommended that only expert PostgreSQL users do so.
[CloudNativePG Documentation - postgresql section](https://cloudnative-pg.io/documentation/1.16/postgresql_conf/)

The problem you are describing is not simply about the default being empty, but about how CNPG handles shared_preload_libraries specifically during the bootstrap.recovery process.

In recovery bootstraps, CNPG generates a temporary postgresql.conf dynamically, and the operator-provided shared_preload_libraries from the manifest is not reliably injected during this bootstrap phase. This means that even if you specify it properly in the cluster manifest like you did:

```yaml
postgresql:
  shared_preload_libraries:
    - timescaledb
```

It does not necessarily get picked up during the recovery. This is why you observe SHOW shared_preload_libraries; returning an empty string '' while still in recovery mode.

So what you are likely running into is not that your configuration is wrong, but that the extension simply can’t preload because CNPG defers loading some settings until the cluster exits recovery and gets promoted.

On top of that, TimescaleDB specifically must be present in shared_preload_libraries before PostgreSQL starts, it cannot be added later dynamically, otherwise you will always get:

```console
ERROR: extension "timescaledb" must be preloaded.
```

The reason your production cluster works is because it was likely created using the normal bootstrap (not bootstrap.recovery), so CNPG applies the manifest’s shared_preload_libraries properly at the start.

Now i hope my understanding above is correct, although i did not have enough time to go through the code for bootstrap recovery to get confirmation, but this is my understanding from observing the behaviour so far. Maybe someone else know knows CNPG better and internals can comment on this one.

A workaround could be to inject the preload library configuration directly into `postgresql.auto.conf` during image build. PostgreSQL always loads `postgresql.auto.conf` at startup, even when under CNPG’s recovery bootstrap, and CNPG does not overwrite it.

For example:

```dockerfile
FROM ghcr.io/imusmanmalik/timescaledb-postgis:15-3.4-42

RUN echo "shared_preload_libraries = 'timescaledb'" >> /usr/share/postgresql/postgresql.auto.conf && \
    echo "shared_preload_libraries = 'timescaledb'" >> /usr/share/postgresql/postgresql.conf.sample
```

This ensures that even during recovery, the TimescaleDB extension will be preloaded correctly. If you could verify this works we could consider adding this to the image which others could benefit from it as well as to my knowledge with CNPG this seems to be a workaround and native functionality is not provided at the time of writing.

After the promotion, CNPG will continue to apply your manifest-defined settings and you will be able to CREATE EXTENSION timescaledb; without issue.
